# Generated by Django 6.0.1 on 2026-02-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_followus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='FollowUS',
        ),
    ]
